-- Tabla de usuarios
CREATE TABLE IF NOT EXISTS User (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabla de rifas
CREATE TABLE IF NOT EXISTS Rifa (
  id INT PRIMARY KEY AUTO_INCREMENT,
  numero VARCHAR(255) UNIQUE NOT NULL,
  descripcion TEXT,
  ganador VARCHAR(255),
  estado VARCHAR(50) DEFAULT 'activo',
  userId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  INDEX idx_user_id (userId),
  INDEX idx_numero (numero),
  INDEX idx_estado (estado)
);
